In [20]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [21]:
mp_key = "KcpGNlNwBWUwWN6pcJS1SzDUsDUsCA2z"
mp_id = "mp-2286"

In [22]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [23]:
#Première symétrie -> symétrie centrale avec le centre de la maille
i_atom = 1 #atome mauve de Li 
i_symmop = 2 #'-x, -y, -z' 
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


In [24]:
#Position initiale de l'atome considéré
pos_init = conv_struc.sites[i_atom -1].frac_coords
print(pos_init)

[0.25 0.25 0.75]


In [25]:
#Position finale de l'atome considéré
pos_final = symmop.operate(pos_init)
print(pos_final)

[-0.25 -0.25 -0.75]


In [26]:
#Représentation de la première symétrie
view = quick_view(conv_struc, "packed", conventional = True)
display(view)
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [27]:
#Deuxième symétrie -> rotation de 90° autour de l'axe (0,0,1)
i_atom = 10 #atome orange de Se au centre d'une face
i_symmop = 17 #'z, x, y'
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
tau
[0. 0. 0.]


In [28]:
#Position initiale de l'atome considéré
pos_init = conv_struc.sites[i_atom -1].frac_coords
print(pos_init)

[0.  0.5 0.5]


In [29]:
#Position finale de l'atome considéré
pos_final = symmop.operate(pos_init)
print(pos_final)

[0.5 0.  0.5]


In [32]:
#Représentation de la deuxième symétrie
view = quick_view(conv_struc, "packed", conventional = True)
display(view)
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [33]:
#Troisième symétrie -> translation
i_atom = 3 #atome mauve de Li
i_symmop = 49 #'x+1/2, y+1/2, z'
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0.5 0.5 0. ]


In [34]:
#Position initiale de l'atome considéré
pos_init = conv_struc.sites[i_atom -1].frac_coords
print(pos_init)

[0.25 0.75 0.25]


In [35]:
#Position finale de l'atome considéré
pos_final = symmop.operate(pos_init)
print(pos_final)

[0.75 1.25 0.25]


In [36]:
#Représentation de la troisième symétrie
view = quick_view(conv_struc, "packed", conventional = True)
display(view)
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))