In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
mp_key = "KcpGNlNwBWUwWN6pcJS1SzDUsDUsCA2z"
mp_id = "mp-2286"

In [3]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [18]:
i_atom = 1
i_symmop = 2

In [22]:
view = quick_view(prim_struc, "packed", conventional = True)
display(view)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [23]:
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

In [24]:
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


In [25]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
print(pos_init)

[0.25 0.25 0.75]


In [26]:
pos_final = symmop.operate(pos_init)
print(pos_final)

[-0.25 -0.25 -0.75]


In [27]:
for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1
print(j_atom, conv_struc.sites[j_atom -1].frac_coords)

2 [0.75 0.75 0.25]


In [28]:
i_atom = 2
i_symmop = 17

In [29]:
view = quick_view(prim_struc, "packed", conventional = True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [30]:
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

In [31]:
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
tau
[0. 0. 0.]


In [32]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
print(pos_init)

[0.75 0.75 0.25]


In [33]:
pos_final = symmop.operate(pos_init)
print(pos_final)

[0.25 0.75 0.75]


In [34]:
for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1
print(j_atom, conv_struc.sites[j_atom -1].frac_coords)

6 [0.25 0.75 0.75]


In [35]:
i_atom = 3
i_symmop = 49

In [36]:
view = quick_view(prim_struc, "packed", conventional = True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [37]:
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

In [38]:
symmop = symmops[i_symmop - 1]
print(symmop)

Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0.5 0.5 0. ]


In [39]:
pos_init = conv_struc.sites[i_atom -1].frac_coords
print(pos_init)

[0.25 0.75 0.25]


In [40]:
pos_final = symmop.operate(pos_init)
print(pos_final)

[0.75 1.25 0.25]


In [41]:
for k_atom, site in enumerate(conv_struc.sites):
    if np.linalg.norm((site.frac_coords - pos_final)%1) < 1e-6:
        j_atom = k_atom + 1
print(j_atom, conv_struc.sites[j_atom -1].frac_coords)

5 [0.75 0.25 0.25]
